# -*- coding: utf-8 -*-
"""generate_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19kIGNmkb8Ct4Pe_qsGty0gKGHE89IAda
"""

import pandas as pd

def generate_synthetic_data(num_samples=10000):
    np.random.seed(42)  # Set seed for reproducibility

    # Generating synthetic data for features
    SK_ID_CURR = np.arange(1, num_samples+1)  # Unique ID for each sample
    AMT_INCOME_TOTAL = np.random.normal(30000, 15000, num_samples)  # Normal distribution for income
    AMT_CREDIT = np.random.normal(200000, 50000, num_samples)  # Normal distribution for credit amount
    DAYS_BIRTH = np.random.randint(20*365, 60*365, num_samples)  # Age between 20 to 60 years
    DAYS_EMPLOYED = np.random.randint(-10*365, 0, num_samples)  # Employment history in days
    TARGET = np.random.choice([0, 1], size=num_samples, p=[0.8, 0.2])  # Random binary target (80% non-default, 20% default)

    # Creating a DataFrame
    df = pd.DataFrame({
        'SK_ID_CURR': SK_ID_CURR,
        'AMT_INCOME_TOTAL': AMT_INCOME_TOTAL,
        'AMT_CREDIT': AMT_CREDIT,
        'DAYS_BIRTH': DAYS_BIRTH,
        'DAYS_EMPLOYED': DAYS_EMPLOYED,
        'TARGET': TARGET
    })

    # Convert DAYS_BIRTH and DAYS_EMPLOYED from days to years
    df['DAYS_BIRTH'] = df['DAYS_BIRTH'] / 365
    df['DAYS_EMPLOYED'] = df['DAYS_EMPLOYED'] / 365

    # Handle outliers by clipping
    df['AMT_INCOME_TOTAL'] = np.clip(df['AMT_INCOME_TOTAL'], 0, 500000)
    df['AMT_CREDIT'] = np.clip(df['AMT_CREDIT'], 0, 500000)

    # Save the synthetic data to a CSV file
    df.to_csv("synthetic_data.csv", index=False)
    print("Synthetic data generation complete. File saved as 'synthetic_data.csv'.")

generate_synthetic_data(40000)